package com.kevin.financeguardian.ui.theme

import androidx.compose.ui.graphics.Color

// ── Material 3 Palette ─ Seed: #0088CC (Telegram Blue) ──────────────────────

// Light scheme
val md_theme_light_primary = Color(0xFF006590)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC8E6FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E2F)
val md_theme_light_secondary = Color(0xFF4F616E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD2E5F5)
val md_theme_light_onSecondaryContainer = Color(0xFF0B1D29)
val md_theme_light_tertiary = Color(0xFF5F5A7D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE5DEFF)
val md_theme_light_onTertiaryContainer = Color(0xFF1C1736)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF6FAFE)
val md_theme_light_onBackground = Color(0xFF181C20)
val md_theme_light_surface = Color(0xFFF6FAFE)
val md_theme_light_onSurface = Color(0xFF181C20)
val md_theme_light_surfaceVariant = Color(0xFFDDE3EA)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_outline = Color(0xFF71787E)
val md_theme_light_outlineVariant = Color(0xFFC1C7CE)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF2D3135)
val md_theme_light_inverseOnSurface = Color(0xFFEEF1F6)
val md_theme_light_inversePrimary = Color(0xFF8BCEFF)
val md_theme_light_surfaceDim = Color(0xFFD6DAE0)
val md_theme_light_surfaceBright = Color(0xFFF6FAFE)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF0F4F8)
val md_theme_light_surfaceContainer = Color(0xFFEAEEF3)
val md_theme_light_surfaceContainerHigh = Color(0xFFE5E9ED)
val md_theme_light_surfaceContainerHighest = Color(0xFFDFE3E7)

// Dark scheme
val md_theme_dark_primary = Color(0xFF8BCEFF)
val md_theme_dark_onPrimary = Color(0xFF00344D)
val md_theme_dark_primaryContainer = Color(0xFF004C6E)
val md_theme_dark_onPrimaryContainer = Color(0xFFC8E6FF)
val md_theme_dark_secondary = Color(0xFFB6C9D8)
val md_theme_dark_onSecondary = Color(0xFF21333E)
val md_theme_dark_secondaryContainer = Color(0xFF374955)
val md_theme_dark_onSecondaryContainer = Color(0xFFD2E5F5)
val md_theme_dark_tertiary = Color(0xFFC9C2EA)
val md_theme_dark_onTertiary = Color(0xFF312C4C)
val md_theme_dark_tertiaryContainer = Color(0xFF474264)
val md_theme_dark_onTertiaryContainer = Color(0xFFE5DEFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0F1417)
val md_theme_dark_onBackground = Color(0xFFDFE3E7)
val md_theme_dark_surface = Color(0xFF0F1417)
val md_theme_dark_onSurface = Color(0xFFDFE3E7)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C7CE)
val md_theme_dark_outline = Color(0xFF8B9198)
val md_theme_dark_outlineVariant = Color(0xFF41484D)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFDFE3E7)
val md_theme_dark_inverseOnSurface = Color(0xFF2D3135)
val md_theme_dark_inversePrimary = Color(0xFF006590)
val md_theme_dark_surfaceDim = Color(0xFF0F1417)
val md_theme_dark_surfaceBright = Color(0xFF353A3E)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0A0F12)
val md_theme_dark_surfaceContainerLow = Color(0xFF181C20)
val md_theme_dark_surfaceContainer = Color(0xFF1C2024)
val md_theme_dark_surfaceContainerHigh = Color(0xFF262A2F)
val md_theme_dark_surfaceContainerHighest = Color(0xFF31353A)

// ── Extended Financial Semantic Colors ───────────────────────────────────────

// Income (green)
val IncomeLight = Color(0xFF1B7D46)
val OnIncomeLight = Color(0xFFFFFFFF)
val IncomeContainerLight = Color(0xFFA8F5C8)
val IncomeDark = Color(0xFF6CD99B)
val OnIncomeDark = Color(0xFF003919)
val IncomeContainerDark = Color(0xFF005228)

// Expense (red) — mirrors error tones but distinct tokens
val ExpenseLight = Color(0xFFBA1A1A)
val OnExpenseLight = Color(0xFFFFFFFF)
val ExpenseContainerLight = Color(0xFFFFDAD6)
val ExpenseDark = Color(0xFFFFB4AB)
val OnExpenseDark = Color(0xFF690005)
val ExpenseContainerDark = Color(0xFF93000A)

// Savings (blue accent)
val SavingsLight = Color(0xFF006590)
val SavingsDark = Color(0xFF8BCEFF)

// Transfers (purple/tertiary)
val TransferLight = Color(0xFF5F5A7D)
val TransferDark = Color(0xFFC9C2EA)

// Warning (amber)
val WarningLight = Color(0xFF7D5800)
val WarningContainerLight = Color(0xFFFFDEA6)
val WarningDark = Color(0xFFFFBF47)
val WarningContainerDark = Color(0xFF5C4100)

// Unknown / uncategorized
val UnknownLight = Color(0xFF71787E)
val UnknownDark = Color(0xFF8B9198)

// ── Balance Card ────────────────────────────────────────────────────────────

val BalanceCardBackgroundLight = Color(0xFF006590)
val OnBalanceCardLight = Color(0xFFFFFFFF)
val BalanceCardBackgroundDark = Color(0xFF004C6E)
val OnBalanceCardDark = Color(0xFFE0F0FF)

// ── Flow Status Badges ─────────────────────────────────────────────────────

// Matched (green-tinted)
val MatchedBadgeLight = Color(0xFF1B7D46)
val MatchedBadgeContainerLight = Color(0xFFD5F5E3)
val MatchedBadgeDark = Color(0xFF6CD99B)
val MatchedBadgeContainerDark = Color(0xFF0D3B1E)

// Pending (amber-tinted)
val PendingBadgeLight = Color(0xFF7D5800)
val PendingBadgeContainerLight = Color(0xFFFFF3D6)
val PendingBadgeDark = Color(0xFFFFBF47)
val PendingBadgeContainerDark = Color(0xFF3D2C00)

// Needs Review (orange-red)
val ReviewBadgeLight = Color(0xFFC35415)
val ReviewBadgeContainerLight = Color(0xFFFFE4D6)
val ReviewBadgeDark = Color(0xFFFFAB80)
val ReviewBadgeContainerDark = Color(0xFF4A1F00)

// Neutral (for internal transfer amounts)
val NeutralAmountLight = Color(0xFF41484D)
val NeutralAmountDark = Color(0xFFC1C7CE)
